export const DATA_SECOND_HOME_PAGE = "DATA_SECOND_HOME_PAGE";
export const REQUEST_SECOND_HOME_PAGE = "REQUEST_SECOND_HOME_PAGE";
export const SUCCESS_SECOND_HOME_PAGE = "SUCCESS_SECOND_HOME_PAGE";
export const FAIL_SECOND_HOME_PAGE = "FAIL_SECOND_HOME_PAGE";