export const GET_SYSTEM_CINEMA_REQUEST =
  "showTimeReducer/GET_SYSTEM_CINEMA_REQUEST";
export const GET_SYSTEM_CINEMA_SUCCESS =
  "showTimeReducer/GET_SYSTEM_CINEMA_SUCCESS";
export const GET_SYSTEM_CINEMA_FAILED =
  "showTimeReducer/GET_SYSTEM_CINEMA_FAILED";
export const GET_DETAIL_LIST_CINEMA_REQUEST =
  "showTimeReducer/GET_DETAIL_LIST_CINEMA_REQUEST";
export const GET_DETAIL_LIST_CINEMA_SUCCESS =
  "showTimeReducer/GET_DETAIL_LIST_CINEMA_SUCCESS";
export const GET_DETAIL_LIST_CINEMA_FAILED =
  "showTimeReducer/GET_DETAIL_LIST_CINEMA_FAILED";
