
export const REQUEST_DATA_CUM_RAP = "REQUEST_DATA_CUMRAP";
export const SUCCESS_DATA_CUM_RAP = "SUCCESS_DATA_CUMRAP";
export const FAIL_DATA_CUM_RAP = "FAIL_DATA_CUMRAP";
export const DATA_DETAIL_CUM_RAP = "DATA_DETAIL_CUM_RAP";