export const DATA_MODAL_HOME_PAGE = "DATA_MODAL_HOME_PAGE";
export const REQUEST_DATA_HOME_PAGE = "REQUEST_DATA_HOME_PAGE";
export const SUCCESS_DATA_HOME_PAGE = "SUCCESS_DATA_HOME_PAGE";
export const FAIL_DATA_HOME_PAGE = "FAIL_DATA_HOME_PAGE";